Makefile fixups
make lib was not working properly with the virtual-env flow because we
were not adding the necessary -I flag to find the numpy libraries.
The way this was broken was that if after a `make install` we modified a
.cpp/.hpp file and tried to run a test, test.py would try to run `make
lib` which would fail saying it couldn't find the necessary numpy
headers:

typed_python/_types.cpp:2:10: fatal error: numpy/arrayobject.h: No such file or directory